// ---------------------------------------------------------------------------
// Core data model for the IC Layout Planner.
// Everything on the canvas is an `Element` (discriminated union on `type`).
// Elements are symbolic planning objects — NOT process-accurate layout cells.
// ---------------------------------------------------------------------------

export type Tool =
  | 'select'
  | 'wire'
  | 'rect'
  | 'circle'
  | 'line'
  | 'arrow'
  | 'polyline'
  | 'text'
  | 'measure';

export type LayerId = 'M1' | 'M2' | 'M3';

export type DeviceKind =
  | 'nmos'
  | 'pmos'
  | 'resistor'
  | 'capacitor'
  | 'well'
  | 'guardring'
  | 'block';

export interface Layer {
  id: LayerId;
  name: string;
  color: string;
  visible: boolean;
  locked: boolean;
}

/** Fields shared by every element. `x`/`y` is the element origin in world units. */
export interface ElementBase {
  id: string;
  x: number;
  y: number;
  rotation: number; // degrees, multiples of 90 when rotated via toolbar
  label: string;
  notes: string;
  locked: boolean;
  groupId: string | null;
}

/** Provenance kept on devices generated from an imported SPICE netlist. */
export interface NetlistInfo {
  instance: string;
  model: string;
  cell: string;
  /** Terminal name → net name, in deck order. */
  nets: { terminal: string; net: string }[];
  params: Record<string, string>;
}

export interface DeviceElement extends ElementBase {
  type: 'device';
  kind: DeviceKind;
  width: number;
  height: number;
  color: string;
  /** Metal layer this device belongs to. Used by `block` so a floorplan block
   *  is colored by (and follows the visibility/lock of) a routing layer. */
  layer: LayerId | null;
  /** Present only on devices generated by the netlist importer. */
  netlist?: NetlistInfo;
}

export interface ShapeElement extends ElementBase {
  type: 'shape';
  shape: 'rect' | 'circle' | 'line' | 'arrow' | 'polyline';
  width: number; // bounding box for rect/circle
  height: number;
  points: number[]; // relative to x,y — used by line/arrow/polyline
  stroke: string;
  fill: string;
  strokeWidth: number;
  layer: LayerId | null; // shapes may optionally belong to a metal layer
}

export interface WireElement extends ElementBase {
  type: 'wire';
  points: number[]; // relative to x,y
  strokeWidth: number;
  layer: LayerId;
}

export interface TextElement extends ElementBase {
  type: 'text';
  text: string;
  fontSize: number;
  color: string;
  width: number;
  callout: boolean; // draw a bordered callout box
}

export interface MeasureElement extends ElementBase {
  type: 'measure';
  points: number[]; // [x1,y1,x2,y2] relative to x,y
}

export type Element =
  | DeviceElement
  | ShapeElement
  | WireElement
  | TextElement
  | MeasureElement;

export interface GridSettings {
  size: number;
  snap: boolean;
  visible: boolean;
  showRulers: boolean;
}

export interface ViewState {
  x: number;
  y: number;
  scale: number;
}

/** Serialized project file (JSON import/export + localStorage). */
export interface ProjectFile {
  version: 1;
  name: string;
  elements: Element[];
  layers: Layer[];
  grid: GridSettings;
  savedAt: string;
}
