// ---------------------------------------------------------------------------
// Core data model for the IC Layout Planner.
// Everything on the canvas is an `Element` (discriminated union on `type`).
// Elements are symbolic planning objects — NOT process-accurate layout cells.
//
// All coordinates and sizes are in nanometres (see `lib/units.ts`); the display
// unit is a view setting and never changes what is stored.
// ---------------------------------------------------------------------------

import type { Unit } from './lib/units';

export type { Unit } from './lib/units';

export type Tool =
  | 'select'
  | 'wire'
  | 'rect'
  | 'circle'
  | 'line'
  | 'arrow'
  | 'polyline'
  | 'text'
  | 'measure';

export type LayerId = 'M1' | 'M2' | 'M3';

export type DeviceKind =
  | 'nmos'
  | 'pmos'
  | 'resistor'
  | 'capacitor'
  | 'well'
  | 'guardring'
  | 'block';

export interface Layer {
  id: LayerId;
  name: string;
  color: string;
  visible: boolean;
  locked: boolean;
}

/** Fields shared by every element. `x`/`y` is the element origin, in nm. */
export interface ElementBase {
  id: string;
  x: number;
  y: number;
  rotation: number; // degrees, multiples of 90 when rotated via toolbar
  label: string;
  notes: string;
  locked: boolean;
  groupId: string | null;
}

/** Provenance kept on devices generated from an imported SPICE netlist. */
export interface NetlistInfo {
  instance: string;
  model: string;
  cell: string;
  /** Terminal name → net name, in deck order. */
  nets: { terminal: string; net: string }[];
  params: Record<string, string>;
}

export interface DeviceElement extends ElementBase {
  type: 'device';
  kind: DeviceKind;
  width: number;
  height: number;
  color: string;
  /** Metal layer this device belongs to. Used by `block` so a floorplan block
   *  is colored by (and follows the visibility/lock of) a routing layer. */
  layer: LayerId | null;
  /** Present only on devices generated by the netlist importer. */
  netlist?: NetlistInfo;
}

export interface ShapeElement extends ElementBase {
  type: 'shape';
  shape: 'rect' | 'circle' | 'line' | 'arrow' | 'polyline';
  width: number; // bounding box for rect/circle
  height: number;
  points: number[]; // relative to x,y — used by line/arrow/polyline
  stroke: string;
  fill: string;
  strokeWidth: number;
  layer: LayerId | null; // shapes may optionally belong to a metal layer
}

export interface WireElement extends ElementBase {
  type: 'wire';
  points: number[]; // relative to x,y
  strokeWidth: number;
  layer: LayerId;
}

export interface TextElement extends ElementBase {
  type: 'text';
  text: string;
  fontSize: number;
  color: string;
  width: number;
  callout: boolean; // draw a bordered callout box
}

export interface MeasureElement extends ElementBase {
  type: 'measure';
  points: number[]; // [x1,y1,x2,y2] relative to x,y
}

export type Element =
  | DeviceElement
  | ShapeElement
  | WireElement
  | TextElement
  | MeasureElement;

export interface GridSettings {
  /** Snap step, in nm. */
  size: number;
  snap: boolean;
  visible: boolean;
  showRulers: boolean;
}

/**
 * The drawing area. `infinite` is an unbounded canvas; `fixed` fences the
 * layout into a die of a known size, with its top-left corner at the origin —
 * so every in-bounds coordinate is positive, as in a real floorplan.
 */
export interface DieSettings {
  mode: 'infinite' | 'fixed';
  /** Die extents in nm. Kept while in `infinite` mode so toggling is lossless. */
  width: number;
  height: number;
}

export interface ViewState {
  x: number;
  y: number;
  /** Screen pixels per nanometre. */
  scale: number;
}

/**
 * Serialized project file (JSON import/export + localStorage).
 *
 * v1 files predate the nanometre model: their geometry is in screen pixels at
 * 100 % zoom and they have no `die`/`unit`. `migrateProject` upgrades them.
 */
export interface ProjectFile {
  version: 2;
  name: string;
  elements: Element[];
  layers: Layer[];
  grid: GridSettings;
  die: DieSettings;
  /** Display unit for the UI — purely presentational. */
  unit: Unit;
  savedAt: string;
}
